version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 
    commands:
      - echo "Installing dependencies"
      - npm install 

  build:
    commands:
      - echo "Starting build process"
      - npm run build 
      - echo "Build process complete"

  post_build:
    commands:
      - echo "Syncing with S3 bucket"
      - aws s3 sync dist/ s3://mybucket231120241 
      - echo "Deployment to S3 complete"

artifacts:
  files:
    - '**/*' 
  base-directory: dist 
  discard-paths: no

cache:
  paths:
    - node_modules/**/* # Cache dependencies to speed up subsequent builds
